### ISSUE TITLE
How to make each post a separate JSON file

### ISSUE THREAD

**Issue by nogginfuel** [mrbrutti/ChicoBlog#1]
I forked this repo quite a while ago (before the infinite looping, which I need to checkout). But how would I adapt the code so that the pull isn't 1 master JSON file but 1 JSON file per blog post?

**Comment by mrbrutti** [comment]
Interesting,  I need to think about it given the whole concept of this is
that I was all client-side code.

On Wednesday, June 3, 2015, Jef Lippiatt notifications@github.com wrote:

> I forked this repo quite a while ago (before the infinite looping, which I
> need to checkout). But how would I adapt the code so that the pull isn't 1
> master JSON file but 1 JSON file per blog post?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreedomCoder/ChicoBlog/issues/1.

## 

Matias P. Brutti _|_ Founder & Principal Security Researcher
C: +1(561) 206-2731 _|_ E: matiasbrutti@gmail.com

**Comment by nogginfuel** [comment]
Thanks for the quick response. I'm debating using this approach or potentially a tiny flat file Markdown format for a simple blog I'm adding to a site.

**Comment by mrbrutti** [comment]
I thought of some quick solutions and still keep the full client-side implementation:
1) one master json with only the names of the files you want to load. and then just iterate through the files. 
2) have the posts under a directory /posts that is directory browseable and have a hackery listing and then parse them that way. 
3 Potentially look into using http://www.html5rocks.com/en/tutorials/file/filesystem/

In any case, interesting problem. I'll work something out, but this is an enhancement and ChicoBlog, in all honesty is not a priority. If you find a solution I will gladly approve the PR. .

**Comment by nogginfuel** [comment]
Thanks for the ideas and response. I'll look into some of those ideas.
